### ISSUE TITLE
Generate visual results

### ISSUE THREAD

**Issue by guopifen** [pengzhou1108/RGB-N#10]
Hi，
when i trained and tested the synthetic dataset(as follows)
![image](https://user-images.githubusercontent.com/37428826/53289242-9a1ea100-37ce-11e9-86ea-7656972407f0.png)
How can I generate visual results like this?
![image](https://user-images.githubusercontent.com/37428826/53289272-15805280-37cf-11e9-9f99-2d93c8eaa5bd.png)thank you

**Comment by vinnitu** [comment]
really how?
