### ISSUE TITLE
Training/testing split

### ISSUE THREAD

**Issue by BTajini** [pengzhou1108/RGB-N#13]
Hi,

Is it possible to share the training/testing split txt files of nist and casia database? if not possible, just a few lines to understand the protocol. 

Thank you in advance.

**Comment by BTajini** [comment]
Problem solved! Thanks.

**Comment by heysun0728** [comment]
How do you implement those txt files? What is their format?
`img x1 x2 y1 y2 type` or `img left top right bottom type`
I got a very low score during training. I doubt if my txt file is wrong.

**Comment by BTajini** [comment]
How many iterations have you trained your model for Nist dataset?
Have a look over here for the shape of txt files : https://github.com/pengzhou1108/RGB-N/issues/12
@heysun0728

**Comment by heysun0728** [comment]
@BTajini  Thank you for your reply. I finally achieved the expected accuracy. #12 is very useful.
