### ISSUE TITLE
Where to download NIST16

### ISSUE THREAD

**Issue by zgarlett** [pengzhou1108/RGB-N#18]
Hi I am doing an undergraduate project and I'm looking for the NIST16 dataset. Do you know where to download this?

Maybe COVER dataset as well. I have Columbia and CASIA

Thank you!

Zach

**Comment by pengzhou1108** [comment]
> Hi I am doing an undergraduate project and I'm looking for the NIST16 dataset. Do you know where to download this?
> 
> Maybe COVER dataset as well. I have Columbia and CASIA
> 
> Thank you!
> 
> Zach

Hi Zach,

For NIST 16, please contact with the official organizer for downloading. For COVER, you can simply download the dataset here.
https://github.com/wenbihan/coverage

Hope it helps.
