### ISSUE TITLE
res101_fusion ckpt 

### ISSUE THREAD

**Issue by sunglowzhang** [pengzhou1108/RGB-N#3]
HI @pengzhou1108 , May  I ask  where's the download link of the res101_fusion  model? 
I am following 
'Train on synthetic dataset'  
.....
'Step 3: Specify the dataset, gpu, and network in train_dist_faster.sh as below as run the file:
./train_faster_rcnn.sh 0 coco **res101_fusion** EXP_DIR coco_flip_0001_bilinear_new

**Comment by pengzhou1108** [comment]
> HI @pengzhou1108 , May I ask where's the download link of the res101_fusion model?
> I am following
> 'Train on synthetic dataset'
> .....
> 'Step 3: Specify the dataset, gpu, and network in train_dist_faster.sh as below as run the file:
> ./train_faster_rcnn.sh 0 coco **res101_fusion** EXP_DIR coco_flip_0001_bilinear_new

Hi, 

The step is planned to train on COCO synthetic dataset using ImageNet pre-trained weights. For ImageNet pre-trained weights, you can download here: https://github.com/endernewton/tf-faster-rcnn
 'EXP_DIR coco_flip_0001_bilinear_new' is the directory name where you want to put the model.

**Comment by sunglowzhang** [comment]
Thanks for the explanation.  Understood.
