### ISSUE TITLE
Testing for single image

### ISSUE THREAD

**Issue by saurav4098** [pengzhou1108/RGB-N#6]
Hi Peng,
I have two questions for you.
Ques-1
I trained the model on Coco Synthetic dataset provided by you. I got the attached curve.Is it good enough?
![tamper](https://user-images.githubusercontent.com/5399560/50372376-90709580-05f3-11e9-8e7b-e183c3ca327b.png)

Ques-2
While testing for single image , I have set the classes=2 as below.
net.create_architecture(sess, "TEST",2, tag='default',
                          anchor_scales=ANCHOR_SCALES,anchor_ratios=ANCHOR_RATIOS)
                          
Is that correct??
I am getting the attached scores and boxes. Can you suggest me how to  move forward after scores and boxes calculation
![scores](https://user-images.githubusercontent.com/5399560/50372359-5dc69d00-05f3-11e9-9f99-18e0de40c538.jpeg) 

Thank you in advance.

**Comment by pengzhou1108** [comment]
> Hi Peng,
> I have two questions for you.
> Ques-1
> I trained the model on Coco Synthetic dataset provided by you. I got the attached curve.Is it good enough?
> ![tamper](https://user-images.githubusercontent.com/5399560/50372376-90709580-05f3-11e9-8e7b-e183c3ca327b.png)
> 
> Ques-2
> While testing for single image , I have set the classes=2 as below.
> net.create_architecture(sess, "TEST",2, tag='default',
> anchor_scales=ANCHOR_SCALES,anchor_ratios=ANCHOR_RATIOS)
> 
> Is that correct??
> I am getting the attached scores and boxes. Can you suggest me how to move forward after scores and boxes calculation
> ![scores](https://user-images.githubusercontent.com/5399560/50372359-5dc69d00-05f3-11e9-9f99-18e0de40c538.jpeg)
> 
> Thank you in advance.

Hi,

The result looks good. For single image test, you can take a look at tools/demo.py. Hope it helps.

**Comment by saurav4098** [comment]
Thank you Peng
