### ISSUE TITLE
CPU->GPU Memcpy failed

### ISSUE THREAD

**Issue by liuzheng081** [pengzhou1108/RGB-N#9]
hi ：
when i trained the model , after some steps , here is a problem 

![image](https://user-images.githubusercontent.com/10113362/51594728-0155e680-1eed-11e9-94e0-698e2cda0d55.png)
i have no idea about that  can you help me.
thank you

**Comment by guopifen** [comment]
i had the same problem and the reason is the GPU's memory is not enough,you can reduce the RPN batch size to save memory

**Comment by guopifen** [comment]
hi,i am a postgraduate who focused on image forgery detection, I'm reproducing this network, too. can you add my wechat so i can ask about you. My wechat: L691017063

**Comment by liuzheng081** [comment]
> hi,i am a postgraduate who focused on image forgery detection, I'm reproducing this network, too. can you add my wechat so i can ask about you. My wechat: L691017063

**Comment by liuzheng081** [comment]
> hi,i am a postgraduate who focused on image forgery detection, I'm reproducing this network, too. can you add my wechat so i can ask about you. My wechat: L691017063

thank you . i had run this network later i will add your wechat. thank you all the way
